### PR TITLE
Fix #1783: Support non-root install in pure mode

### LINKED ISSUE #1783: Support non-root setup
### What problem are you trying to solve?

I use nix-portable since I cannot use sudo/su on my work system due to security policy. devbox tries to install on /usr/local/bin, which requires root access. It also tries to install nix as root if the nix command is not available.

Even when `nix` is available via `nix-portable`, some functionalities do not seem to work as expected, such as `devbox shell --pure`:
```
Error: could not find any nix executable in PATH. Make sure Nix is installed and in PATH, then try again
```
`nix` is available as binary in PATH, so the message is wrong, and the problem has been triggered by a different issue, probably.

### What solution would you like?

I modified the setup script to target ~/.local/bin and linked nix-portable to nix. It would be nice to be able to specify a different installation path and use sudo only whenever it is needed. Giving proper documentation on how to install devbox with nix-portable would be a plus.

### Alternatives you've considered

_No response_

### PR DESCRIPTION
**Pull request by kadaan**
## Summary
Fix #1783: Support non-root install in pure mode

## How was it tested?
Ran `devbox shell` and `devbox shell --pure` and they both work now with my non-root install of nix on MacOS.

### CODE REVIEW

**Comment by savil** [comment]
thanks for sending this PR as well!

File: internal/devbox/devbox.go [hunk 1]
```diff
@@ -1262,12 +1262,11 @@ func (d *Devbox) parseEnvAndExcludeSpecialCases(currentEnv []string) (map[string
 		// Finding nix executables in path and passing it through
 		// As well as adding devbox itself to PATH
 		// Both are needed for devbox commands inside pure shell to work
-		includedInPath, err := findNixInPATH(env)
+		nixPath, err := findNixInPATH()
```
Comment (gcurtis) [inline internal/devbox/devbox.go:1265]: If `findNixInPATH` is only ever called with `os.Environ()`, then I think we should just remove it and simplify this down to:

```suggestion
		nixPath, err := exec.LookPath("nix")
		if err != nil {
				return "", errors.New("could not find any nix executable in PATH. Make sure Nix is installed and in PATH, then try again")
		}
		nixPath = filepath.Dir(nixPath)
```

**Comment by kadaan** [comment]
@gcurtis Any other feedback?

**Review by gcurtis — APPROVED** [review]
Thanks for the changes! This looks good. I'll merge after tests finish.

**Review by savil — APPROVED** [review]

**Comment by kadaan** [comment]
Thanks for the reviews and merging!
