### PR TITLE
[nix profile] Changes to support format changes from nix 2.20

### LINKED ISSUE #1767: Failing to add packages due to Go unmarshalling error
### What happened?

After running `devbox init`, I attempt to add any package to it via `devbox add` but it fails with an unmarshalling error. Presumably it's trying to deserialize some JSON but Nix updated the format or something? I had Nix installed on my machine already, so maybe it's an incompatible version or something.

### Steps to reproduce

1. Install Nix on MacOS using their official installer: https://nixos.org/download#nix-install-macos
2. Install devbox via the official script: https://www.jetpack.io/devbox/docs/quickstart/
3. Run `devbox init` to start a `devbox.json`
4. Run `devbox add go` to add the go package to `devbox.json`

### Command

add

### devbox.json

```jsonc
{
  "packages": [],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.8.7

### Nix version

2.20.1

### What system does this bug occur on?

macOS (Intel)

### Debug logs

I've edited the output to mask some file names, but semantically it's the same.

2024/01/31 15:59:37 findProjectDir: path is
2024/01/31 15:59:37 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
2024/01/31 15:59:37 findProjectDir: path is
2024/01/31 15:59:37 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
2024/01/31 15:59:38 findProjectDir: path is
2024/01/31 15:59:38 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
Info: Adding package "go@latest" to devbox.json

Error: There was an error installing nix packages
source: json: cannot unmarshal object into Go struct field ProfileListOutput.elements of type []nixprofile.ProfileListElement

2024/01/31 15:59:38
ExecutionID:1e390847f87b4708b43062a4736f5eed
<nil>
2024/01/31 15:59:38 findProjectDir: path is
2024/01/31 15:59:38 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO

### PR DESCRIPTION
**Pull request by savil**
## Summary

The latest nix version (2.20) changed how the nix profile output is represented:

From the [release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.20):

> nix profile now allows referring to elements by human-readable names https://github.com/NixOS/nix/pull/8678

> [nix profile](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile) now uses names to refer to installed packages when running [list](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-list), [remove](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-remove) or [upgrade](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-upgrade) as opposed to indices. Profile element names are generated when a package is installed and remain the same until the package is removed.

> Warning: The manifest.nix file used to record the contents of profiles has changed. Nix will automatically upgrade profiles to the new version when you modify the profile. After that, the profile can no longer be used by older versions of Nix.

and for `nix search`:
> Disallow empty search regex in nix search [#9481](https://github.com/NixOS/nix/pull/9481)

> [nix search](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-search) now requires a search regex to be passed. To show all packages, use ^.

TODOs:
- [x] update `nix.readManifest` to handle the new format
- [x] `nix search` requires a regex to be passed
- [x] manually test on nix < 2.20 on devbox.sh to verify the older nix still works

Fixes #1767 

## How was it tested?

CICD should pass

Installed nix 2.20.1 locally and am using Devbox with it to add, remove packages and run scripts and shell.

verified flake updating works:
1.  `examples/flakes/remote`. Did `devbox shell`, dropped the `v0.43.1` from process-compose flake, did `devbox update`, and verified that `process-compose` now had the latest version (IIRC `0.80+`)
2. `examples/flakes/php`. Did `devbox shell`, edited the flake to drop `ds` and did `devbox update`. Verified no `ds` in `php -m | grep ds`

### CODE REVIEW

**Comment by savil** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1770** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1770?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/jetpack-io/devbox/1770?utm_source=stack-comment).

File: internal/nix/nixprofile/profile.go [hunk 1]
```diff
@@ -42,24 +42,46 @@ func ProfileListItems(
...
+				nixStorePaths:     element.StorePaths,
+			})
+		}
+		return items, nil
 	}
+	// Fall back to trying format for nix < version 2.20
 
+	// ProfileListOutput for nix < version 2.20 relied on index instead
+	// of name for each package installed.
+	type ProfileListOutputPreNix2Dot20 struct {
```
Comment (savil) [inline internal/nix/nixprofile/profile.go:67]: Will rename to `ProfileListOutputLegacy`

File: internal/nix/nixprofile/profile_test.go [hunk 2]
```diff
@@ -49,10 +49,10 @@ func TestNixProfileListItem(t *testing.T) {
...
 			expected: expectedTestData{
 				item: &NixProfileListItem{
-					2,
-					"github:NixOS/nixpkgs/52e3e80afff4b16ccb7c52e9f0f5220552f03d04#legacyPackages.x86_64-darwin.python39Packages.numpy",
-					"github:NixOS/nixpkgs/52e3e80afff4b16ccb7c52e9f0f5220552f03d04#legacyPackages.x86_64-darwin.python39Packages.numpy",
-					[]string{"/nix/store/qly36iy1p4q1h5p4rcbvsn3ll0zsd9pd-python3.9-numpy-1.23.3"},
+					index:             2,
+					unlockedReference: "github:NixOS/nixpkgs/52e3e80afff4b16ccb7c52e9f0f5220552f03d04#legacyPackages.x86_64-darwin.python39Packages.numpy",
+					lockedReference:   "github:NixOS/nixpkgs/52e3e80afff4b16ccb7c52e9f0f5220552f03d04#legacyPackages.x86_64-darwin.python39Packages.numpy",
+					nixStorePaths:     []string{"/nix/store/qly36iy1p4q1h5p4rcbvsn3ll0zsd9pd-python3.9-numpy-1.23.3"},
```
Comment (savil) [inline internal/nix/nixprofile/profile_test.go:55]: should add a test-case with `name:` field

Comment (savil) [reply internal/nix/nixprofile/profile_test.go:55]: actually, this test is for legacy `nix profile list` parsing. Not the modern --json output. Renamed to clarify.
