### PR TITLE
Fix #1868: Fix flake handling

### LINKED ISSUE #1868: devbox update fail when git flake are present
### What happened?

Running `devbox update` fails when git flakes are present in the `devbox.json`.

### Steps to reproduce

1.  Add git flake to devbox.json
2. Run devbox shell
3. Exit shell
4. Run devbox update

### Command

_No response_

### devbox.json

```jsonc
{
  "packages": [
    "git+ssh://git@bitbucket.org/foo/bar.git#baz"
  ],
}
```

### Devbox version

0.9.1

### Nix version

2.19.3

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

2024/02/29 17:53:38 findProjectDir: path is
2024/02/29 17:53:38 finding devbox config in dir: /source/work/joelb_test
2024/02/29 17:53:38 findProjectDir: path is
2024/02/29 17:53:38 finding devbox config in dir: /source/work/joelb_test
2024/02/29 17:53:38 findProjectDir: path is
2024/02/29 17:53:38 finding devbox config in dir: /source/work/joelb_test
Error: git+ssh://git@bitbucket.org/foo/bar.git#baz: package not found

2024/02/29 17:53:39
ExecutionID:2323d1a6d79f4977814fa853ea181384
package not found
go.jetpack.io/devbox/internal/nix.init
	<autogenerated>:1
runtime.doInit1
	/nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/runtime/proc.go:7176
runtime.doInit
	/nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/runtime/proc.go:7143
runtime.main
	/nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/runtime/proc.go:253
runtime.goexit
	/nix/store/2022s0jnrn2iyxjaikfy51w5fvifp38b-go-1.22.0/share/go/src/runtime/asm_arm64.s:1222
2024/02/29 17:53:39 findProjectDir: path is
2024/02/29 17:53:39 finding devbox config in dir: /source/work/joelb_test

### PR DESCRIPTION
**Pull request by kadaan**
## Summary
`devbox update` does not work with git flakes.  This adds support for git flake to `devbox update` and also ensures that the nix packages are rebuilt when an update is requested.  Without this, git flakes will not be refreshed from git.

## How was it tested?

1. Configured a devbox.json with devbox packages and flakes
2. Ran devbox shell without a .devbox folder and without packages being installed in nix
3. Saw packages get installed 
4. Ran devbox shell with a .devbox folder and with packages being installed in nix
5. Saw packages verified, but not updated or installed
6. Ran devbox update
7. Saw packages get rebuild with `nix build --refresh`

### CODE REVIEW

**Comment by savil** [comment]
@kadaan thanks for sending this PR! We'll try to review it later today

File: nix/flake/flakeref.go [hunk 1]
```diff
@@ -103,10 +103,7 @@ func ParseRef(ref string) (Ref, error) {
 		parsed.Path = ref
 		return parsed, nil
 	}
-	parsed, fragment, err := parseURLRef(ref)
-	if fragment != "" {
-		return Ref{}, redact.Errorf("flake reference %q contains a URL fragment", ref)
-	}
```
Comment (gcurtis) [inline nix/flake/flakeref.go:109]: Take a look at `flake.Installable`, which I think does what you need. Flake references can't have attribute paths.

**Comment by kadaan** [comment]
@savil No problem.  Looks like go-lint is failing.  Maybe I missed something on my end in preparing these PRs.  Can you point me to the steps I should run to ensure that the code is formatted, linted, etc. to your standards?

File: internal/devpkg/pkgtype/flake.go [hunk 2]
```diff
@@ -0,0 +1,20 @@
+package pkgtype
+
+import (
+	"go.jetpack.io/devbox/nix/flake"
+	"strings"
+)
+
+func IsFlake(s string) bool {
```
Comment (gcurtis) [inline internal/devpkg/pkgtype/flake.go:8]: I think you can reuse `devpkg.isAmbiguous` here.

In some cases it's impossible to know if a package is a flake without resolving it (for example, `foo` could be an indirect flake's default package or it could be a Devbox package named `foo`).

File: internal/lock/resolve.go [hunk 3]
```diff
@@ -28,6 +28,10 @@ import (
 // a newer hash than the lock file but same version. In that case we don't want
 // to update because it would be slow and wasteful.
 func (f *File) FetchResolvedPackage(pkg string) (*Package, error) {
+	if pkgtype.IsFlake(pkg) {
```
Comment (gcurtis) [inline internal/lock/resolve.go:31]: You'll get some false negatives here, but maybe that's okay? You can know for sure if something is not a Devbox package, but you can't always know for certain if it is a flake.

File: internal/devpkg/package.go [hunk 4]
```diff
@@ -238,7 +238,7 @@ func (p *Package) FlakeInputName() string {
 			}
 		}
 	default:
-		result = p.installable.String() + "-" + p.Hash()
+		result = p.installable.Ref.URL + "-" + p.Hash()
```
Comment (gcurtis) [inline internal/devpkg/package.go:241]: `Ref.URL` isn't quite the same as the flakeref in URL form. It's only set when a flakeref has the type tarball/file/git. You can use `Ref.String()` to get the ref without the attribute path:

```suggestion
		result = p.installable.Ref.String() + "-" + p.Hash()
```

File: internal/devbox/packages.go [hunk 5]
```diff
@@ -479,16 +484,20 @@ func (d *Devbox) packagesToInstallInStore(ctx context.Context) ([]*devpkg.Packag
...
+					return nil, packageInstallErrorHandler(err, pkg, installable)
+				}
+				isInStore, err := nix.StorePathsAreInStore(ctx, storePaths)
+				if err != nil {
+					return nil, err
+				}
+				if !isInStore {
+					packagesToInstall = append(packagesToInstall, pkg)
+				}
 			}
```
Comment (gcurtis) [inline internal/devbox/packages.go:501]: Replace else block with continue:

```
if mode == update {
	packagesToInstall = append(packagesToInstall, pkg)
	continue
}
```

**Comment by Lagoja** [comment]
> @savil No problem. Looks like go-lint is failing. Maybe I missed something on my end in preparing these PRs. Can you point me to the steps I should run to ensure that the code is formatted, linted, etc. to your standards?

You can run `devbox run lint` in the project root to automatically run our linting + formatting

**Review by gcurtis — COMMENTED** [review]
Thanks for the PR. I have some feedback on the flake parsing portion.

File: internal/devpkg/pkgtype/flake.go (hunk 2 above)
Comment (kadaan) [reply internal/devpkg/pkgtype/flake.go:8]: A couple issue here:
1. devpkg.isAmbiguous would need to have it's visibility changed
2. devpkg.isAmbiguous would need to move to a different package because using devpkg in the lock package causes an import cycle

File: nix/flake/flakeref.go (hunk 1 above)
Comment (kadaan) [reply nix/flake/flakeref.go:109]: The code that is deleted here was added as part of https://github.com/jetpack-io/devbox/commit/1dbcad274cddf480a6fab062dee2649a3b726112.  

It seems odd to throw an error when parsing a reference given that a fragment is a valid part of a flake url.  Leaving this code here causes

File: internal/lock/resolve.go (hunk 3 above)
Comment (kadaan) [reply internal/lock/resolve.go:31]: Can you give an example of a package that would be a false negative?

File: nix/flake/flakeref.go (hunk 1 above)
Comment (gcurtis) [reply nix/flake/flakeref.go:109]: Fragments aren't valid in a flake reference, but they are valid in an "installable". They're slightly different, but the distinction is important in some cases. For example:

```
$ nix eval --expr 'builtins.parseFlakeRef "nixpkgs#hello"'
error:
       … while calling the 'parseFlakeRef' builtin

         at «string»:1:1:

            1| builtins.parseFlakeRef "nixpkgs#hello"
             | ^

       error: unexpected fragment 'hello' in flake reference 'nixpkgs#hello'
```

File: internal/lock/resolve.go (hunk 3 above)
Comment (gcurtis) [reply internal/lock/resolve.go:31]: For example, `cachix` is both a Devbox package name and a flake ref:

```
$ devbox search cachix
Found 4+ results for "cachix":

* cachix  (1.7.1, 1.7, 1.6.1, 1.6, 1.5, 1.3.3, 1.4.2, 1.3.1, 1.3, 1.2)
```

```
$ nix flake metadata cachix
Resolved URL:  github:cachix/cachix
Locked URL:    github:cachix/cachix/3a6e4a049f7cadd8894015c2488a2fa969c83c41
```

When we get an ambiguous package name like that, Devbox's behavior is to assume it's a package first and fallback to treating it like a flake second.

File: internal/devpkg/pkgtype/flake.go (hunk 2 above)
Comment (kadaan) [reply internal/devpkg/pkgtype/flake.go:9]: @gcurtis One issue before this PR is that `resolve.FetchResolvedPackage` would call `searcher.ParseVersionedPackage` and that would incorrectly identify `git+ssh://git@foo/bar/baz.git#boo` as a versioned package due to the `@`.  Filtering out known Flakes and leaving ambiguous Flakes is probably good enough at this point.

Comment (kadaan) [reply internal/devpkg/pkgtype/flake.go:9]: I switched to using `ParseInstallable` and `IsAmbiguous` in `pkgtype.IsFlake`.  To do so, I moved `IsAmbiguous` to package `pkgtype`.

File: internal/lock/resolve.go (hunk 3 above)
Comment (kadaan) [reply internal/lock/resolve.go:31]: Perfect.  TY

**Comment by kadaan** [comment]
@gcurtis Any other feedback?

**Review by gcurtis — APPROVED** [review]
This looks good to me. @savil or @mikeland73 I dunno if you guys want to double check the update logic.

**Comment by savil** [comment]
@gcurtis will take a look and merge if all good

**Comment by savil** [comment]
Looks awesome! Did some sanity testing with non-flakes to exercise the `nix build --refresh` flag to verify it doesn't do anything unexpected.

Thank you @kadaan 🙏🏾 !

**Comment by kadaan** [comment]
@savil You are welcome.  Thanks for the reviews and merging!
