### PR TITLE
wrappers] ensure bin-wrappers invoke other binaries and not bin-wrappers

### LINKED ISSUE #1142: [Bug]: Wrappers interfere with `iex -s mix`
**Current Behavior (bug)**

Trying to run `iex -s mix <target>` raises the following exception:

```
iex -S mix phx.server
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

** (SyntaxError) .devbox/virtenv/.wrappers/bin/mix:10:17: invalid character "w" after number 78. If you intended to write a number, make sure to separate the number from the character (using comma, space, etc). If you meant to write a function name or a variable, note that identifiers in Elixir cannot start with numbers. Unexpected token: w
    |
 10 | exec /nix/store/78wdiq951nz7hkhsxnsrmcjrwsvw3ydn-elixir-1.14.3/bin/mix "$@"
    |                 ^
    (elixir 1.14.3) lib/code.ex:1260: Code.require_file/2
```

This is caused by the `iex` parsing the Devbox wrapped mix binary as Elixir code, and erroring out when it encounters the Nix hash. The line above works when the wrapper is bypassed and the store path is referenced directly

`iex -S /nix/store/78wdiq951nz7hkhsxnsrmcjrwsvw3ydn-elixir-1.14.3/bin/mix phx.server`

**Expected Behavior (fix)**
Wrappers should not interfere with binary execution. This bug could affect other situations besides `iex`, so a more general solution for wrappers may be needed

### PR DESCRIPTION
**Pull request by savil**
## Summary

This is an alternate to #1151 (see explanation in #1159)

In this approach, the wrapped-binary always calls:
`eval $(devbox shellenv only-path-without-wrappers)` 
to ensure that the PATH is set without the `wrappers/bin` directory.

In contrast to #1151, we do not always set any other environment variables

Fixes #1142

## How was it tested?

issue from #1142 is fixed:
```
> devbox run -- iex -S mix
* creating .nix-mix/archives/hex-2.0.6
* creating .nix-mix/elixir/1-14/rebar3
Resolving Hex dependencies...
Resolution completed in 0.016s
Unchanged:
  cowboy 2.9.0
  cowlib 2.11.0
  ranch 1.8.0
All dependencies are up to date
Erlang/OTP 25 [erts-13.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Hello World!
Interactive Elixir (1.14.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Goodbye World

17:18:09.349 [notice] Application elixir_hello exited: shutdown

BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
```

- [ ] testscripts should pass

### CODE REVIEW

**Comment by savil** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1159** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1159" target="_blank">Graphite</a> 
    * **PR #1160** <a href="https://app.graphite.dev/github/pr/jetpack-io/devbox/1160" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jetpack-io/devbox/1160?utm_source=stack-comment).

**Review by LucilleH — APPROVED** [review]
LGTM

In this case shellenv will be invoked on every binary call, which is quite SAD.

As a follow up, perhaps we can generate this PATH env variable and store it in a file. In every wrapped binary, we simply source that file. 

The file only needs to be re-generated if `__DEVBOX_SHELLENV_HASH_` does not match.

File: internal/boxcli/shellenv.go [hunk 1]
```diff
@@ -74,7 +77,60 @@ func shellEnvFunc(cmd *cobra.Command, flags shellEnvCmdFlags) (string, error) {
...
+}
+
+type shellEnvOnlyPathWithoutWrappersCmdFlags struct {
+	config configFlags
+}
+
+func shellEnvOnlyPathWithoutWrappersCmd() *cobra.Command {
+	flags := shellEnvOnlyPathWithoutWrappersCmdFlags{}
+	command := &cobra.Command{
+		Use:     "only-path-without-wrappers",
```
Comment (mohsenari) [inline internal/boxcli/shellenv.go:99]: Nit, drop the only and let the command be "path-without-wrappers"

**Review by mohsenari — APPROVED** [review]
Nice. Thank you. Just one nit comment

File: internal/boxcli/shellenv.go (hunk 1 above)
Comment (savil) [reply internal/boxcli/shellenv.go:99]: 🤔 I'd prefer leaving it in to make it clear that this is not also returning other env-vars of shellenv.

**Comment by savil** [comment]
> In this case shellenv will be invoked on every binary call, which will impact performance.

That was the case with the fix in #1151 as well.

I'm not very concerned because a cached `devbox shellenv` is pretty fast (30 milliseconds if I do `time eval $(devbox shellenv)`), and it will 100% be cached in this case. The direnv-inspired solution we are exploring will call `devbox shellenv` on every shell prompt, which is okay, because its fast enough.

File: internal/boxcli/shell.go [hunk 2]
```diff
@@ -59,7 +59,7 @@ func runShellCmd(cmd *cobra.Command, flags shellCmdFlags) error {
 	if flags.printEnv {
 		// false for includeHooks is because init hooks is not compatible with .envrc files generated
 		// by versions older than 0.4.6
-		script, err := box.PrintEnv(cmd.Context(), false /*includeHooks*/)
+		script, err := box.PrintEnv(&devopt.PrintEnv{Ctx: cmd.Context()})
```
Comment (mikeland86) [inline internal/boxcli/shell.go:62]: super golang nit, generally context and struct are passed as 2 args. The reason is that storing context in a struct is risky because we may accidentally keep it in state somewhere.

File: internal/impl/devbox.go [hunk 3]
```diff
@@ -322,9 +322,23 @@ func (d *Devbox) PrintEnv(ctx context.Context, includeHooks bool) (string, error
 		return "", err
 	}
 
+	if opts.OnlyPathWithoutWrappers {
+		path := []string{}
+		for _, p := range strings.Split(envs["PATH"], string(filepath.ListSeparator)) {
```
Comment (mikeland86) [inline internal/impl/devbox.go:327]: `filepath.SplitList` ?

File: internal/wrapnix/wrapper.sh.tmpl [hunk 4]
```diff
@@ -29,4 +29,9 @@ export {{ .ShellEnvHashKey }}_GUARD=true
 eval "$(DO_NOT_TRACK=1 devbox shellenv -c {{ .ProjectDir }})"
 fi
 
+# So that we do not invoke other bin-wrappers from
+# this bin-wrapper. Instead, we directly invoke the binary from the nix store, which
```
Comment (mikeland86) [inline internal/wrapnix/wrapper.sh.tmpl:33]: nit, it's the binary of the profile (which I guess points to the nix store path)

File: internal/boxcli/shell.go (hunk 2 above)
Comment (savil) [reply internal/boxcli/shell.go:62]: good point, this has been undone in a future PR already!

File: internal/wrapnix/wrapper.sh.tmpl (hunk 4 above)
Comment (savil) [reply internal/wrapnix/wrapper.sh.tmpl:33]: the emphasis here is on _binary_ as opposed to _wrapper_
